Style/StringLiterals:
  EnforcedStyle: double_quotes
Metrics/MethodLength:
  Max: 30
Metrics/AbcSize:
  Max: 30
Documentation:
  Enabled: false
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'
Naming/UncommunicativeMethodParamName:
  Enabled: false
Naming/UncommunicativeBlockParamName:
  Enabled: false
